GET http://backend.imersao.fullcycle.com.br/orders
x-token: nwashx2nnej

###
GET http://localhost:3000/orders/75efb3c2-7ac3-4ebf-b8dd-fa89e758c6d7
x-token: uwjv5dqrlpo

###
POST http://backend.imersao.fullcycle.com.br/orders
Content-Type: application/json
x-token: nwashx2nnej

{
    "amount": 1000.33,
    "credit_card_number": "4485460940174065",
    "credit_card_name": "Luiz Carlos",
    "credit_card_expiration_month": 12,
    "credit_card_expiration_year": 2022,
    "credit_card_cvv": "123"
}

###
PATCH http://localhost:3000/orders/64704072-7959-482e-b658-d008612f27e9
Content-Type: application/json

{
    "amount": 1000.33,
    "credit_card_number": "111122222"
}

###
DELETE http://localhost:3000/orders/64704072-7959-482e-b658-d008612f27e9